version: "3.5"

services:
  api01: &api
    build:
      context: .
    hostname: api01
    environment:
      - "PORT=3000"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3000:3000"

  rinha_load_balancer_tcp:
    build:
      context: .
      dockerfile: ./load_balancer_tcp/Dockerfile
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "100MB"

  # rinha_load_balancer_http:
  #   build:
  #     context: .
  #     dockerfile: ./load_balancer_http/Dockerfile
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.9"
  #         memory: "100MB"

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api01
  #     - api02
  #   ports:
  #     - "9999:9999"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "1"
  #         memory: "100MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

