[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcode = { version = "0.6.3", features = ["serde"] }
serde = { version = "1.0.203", features = ["derive"] }

[dev-dependencies]
tempfile = "3.10.1"
